### ISSUE TITLE
兄弟，ios上边下拉刷新不正常 。您可以测试下

### ISSUE THREAD

**Issue by Gttma** [RickyHal/yy-refresh#1]

**Comment by RickyHal** [comment]
收到，我去看下



---原始邮件---
发件人: "tmy"<notifications@github.com&gt;
发送时间: 2019年10月22日(星期二) 下午5:50
收件人: "RickyHal/yy-refresh"<yy-refresh@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [RickyHal/yy-refresh] 兄弟，ios上边下拉刷新不正常 。您可以测试下 (#1)

**Comment by 110117ab** [comment]
解决了嘛，楼主？

**Comment by Gttma** [comment]
> 解决了嘛，楼主？

此插件确实存在这个问题，按照官方demo里边的写法就可以
